version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./done-before.txt:/app/done-before.txt
      - ./output:/app/output
    depends_on:
      - db
    env_file: .env
  db:
    image: mariadb:latest
    env_file: .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: Jdon My Soul
      MARIADB_DATABASE: sc-stats
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
